### ISSUE TITLE
Security review of endpoints

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1401]
### Desired behaviour

Before implementing private repo refresh, it would probably be good to take a close look at all endpoints for potential security gaps. Test out whether our CORS setup is appropriate, whether we're using U2F everywhere that is appropriate, etc.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-78)
┆Sprint: Lighthouse Sprint 34 Hepsidam
┆Issue Number: DOCK-78

**Comment by agduncan94** [comment]
Hidden is probably not working how we think. I've fixed it in the UI so that a hidden version is hidden in public, but it will not be hidden from the webservice. Unfortunately we use the same endpoint for my tools and tools, so we might have to create two versions of the endpoint, one authenticated and the other not.

I think we use the /workflow/versions endpoint

**Comment by denis-yuen** [comment]
In discussion: the other possibility is to use the endpoint in an authenticated fashion for my tools/my workflows and without authentication otherwise and have the endpoint take that into account

**Comment by denis-yuen** [comment]
Kicking this back to backlog. 
Probably good to get another set of eyes on this

**Comment by coverbeck** [comment]
First thought: I don't believe CSRF is an issue, as authentication for Ajax calls is done by explicitly setting the Authorization header and does not rely on a cookie. See https://security.stackexchange.com/questions/62080/is-csrf-possible-if-i-dont-even-use-cookies

**Comment by coverbeck** [comment]
Small issue

The caching authenticator is configured with an expiration of 10 minutes.

If a user made a Dockstore API call with a Google token that was just about to expire, the user would still have access to Dockstore API for a full 10 minutes, even with the expired token.

**Comment by coverbeck** [comment]
I am done with my portion of the review.
